import type { Metadata } from "next";
import Header from "./headers";
import Footer from "./footer";

export const metadata: Metadata = {
  title: {
    default: "Home page",
    template: "%s | Next App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div >
            <Header/>
            <div className="h-screen content-between">
                <div className="h-5/6 pt-20 p-5">
                    {children}
                </div>
                <div className="h-1/6 p-5 flex justify-center w-full bg-violet-950 text-violet-300">
                    <Footer/>
                </div>
            </div>
        </div>
    </>
  );
}
